/**
 * Generates src/environments/environment.prod.ts from NG_APP_API_URL env var.
 * Run automatically via the "prebuild" npm script before `ng build`.
 */
const fs = require('fs');
const path = require('path');

const apiUrl = (process.env['NG_APP_API_URL'] || '').trim();
const content = `// Auto-generated by scripts/set-env.js — do not edit manually.
// Set NG_APP_API_URL in your build environment (Vercel env var, CI secret, etc.)
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('environment.prod.ts generated — apiUrl:', apiUrl || '(empty, set NG_APP_API_URL)');
