// Auto-generated by scripts/set-env.js — do not edit manually.
// Set NG_APP_API_URL in your build environment (Vercel env var, CI secret, etc.)
export const environment = {
  production: true,
  apiUrl: '',
};
